apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operands-frankfurt
spec:
  generators:
  - list:
      elements:
        - name: platformnavigator
          namespace: cp4i
          sync-wave: "200"
        - name: mq
          namespace: cp4i
          sync-wave: "300"
        - name: openshift-logging
          namespace: openshift-logging
          sync-wave: "200"
        - name: openshift-monitoring
          namespace: openshift-monitoring
          sync-wave: "200"
        - name: reloader
          namespace: cp4i
          sync-wave: "200"
  template:
    metadata:
      name: '{{name}}'
      labels:
        group: applications
      annotations:
        argocd.argoproj.io/sync-wave: '{{sync-wave}}'
    spec:
      project: cp4i-operands
      source:
        path: 'envs/odf/frankfurt/{{name}}/'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          selfHeal: true
      ignoreDifferences:
          
      # App Connect operator adds xxx-adminssl Configuration which is not in our 
      # manifest. Ignore this so Argo treats the app as synced. We can't add this to the
      # manifest since a validation webhook checks that the config is available, which it won't be on
      # first creation of the IntegrationRuntime or if it gets deleted.
      - group: appconnect.ibm.com
        kind: IntegrationRuntime
        jqPathExpressions:
          - .spec.configurations[] | select(. | endswith("ir-adminssl"))

      # Ignore replicas so HPA can be used.
      - group: appconnect.ibm.com
        kind: IntegrationRuntime
        jsonPointers:
        - /spec/replicas
